---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uby/u9bot_main/
    - export DEPLOYPATHFROM=/home/uby/u9bot/
    - /bin/c README.md ${DEPLOYPATH}
    - /bin/c passenger_wsgi.py ${DEPLOYPATH}
    #Add /<sub_folder> if required
    # use - /bin/cp -R images $DEPLOYPATH  to copy images folder