---
deployment:
  tasks:
    - export DEPLOYPATH=/home/uby/u9bot_main/
    - passenger_wsgi.py $DEPLOYPATH
    #Add /<sub_folder> if required
    # use - /bin/cp -R images $DEPLOYPATH  to copy images folder